minimum_pre_commit_version: 2.20.0
default_stages: [commit, push]
exclude: '^$'
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: double-quote-string-fixer
    - id: check-docstring-first
    - id: check-yaml
    - id: debug-statements
    - id: name-tests-test
    - id: requirements-txt-fixer
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.7.0
    hooks:
    - id: autopep8
